### ISSUE TITLE
Install psutil on Heroku deploy

### ISSUE THREAD

**Issue by dealien** [dealien/Red-Magician#59]
Required for [sysinfo.py](../blob/master/cogs/sysinfo.py)
```
Traceback (most recent call last):
  File "red.py", line 639, in load_cogs
    owner_cog._load_cog(extension)
  File "/app/cogs/owner.py", line 974, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "lib/discord/ext/commands/bot.py", line 738, in load_extension
    lib.setup(self)
  File "/app/cogs/sysinfo.py", line 110, in setup
    raise RuntimeError("You need to run 'pip3 install psutil'")
RuntimeError: You need to run 'pip3 install psutil'
```

**Comment by dealien** [comment]
Possibly related to changes made in 99ceadcb65681963e629c7e807a294717a5d1b92 for #53. The issue was fixed in my local installation by removing `lib/` from tracking (which wasn't supposed to be tracking in the first place). This may have also fixed the issue for Heroku-deployed instances as well, however, it has not been tested since the changes were made.

**Comment by dealien** [comment]
I tested it and it works. Here's hoping it continues to work from now on...
